#!/usr/bin/env bash
# Refresh CouchDB's JWT key set with Google's current RS256 signing keys.
#
# Google rotates keys roughly every day, so this needs to run on a schedule
# (e.g. a cron job every few hours) in any environment that uses Google ID
# tokens to authenticate to CouchDB.
#
# Output goes to couchdb/jwt-keys.ini, which docker-compose mounts read-only
# into the running CouchDB container at
# /opt/couchdb/etc/local.d/20-jwt-keys.ini. CouchDB picks up changes to that
# file on its own; if you want changes to apply immediately, restart the
# container.
#
# Requires: bash, curl, jq, openssl. The Google client ID is read from the
# environment (VITE_GOOGLE_CLIENT_ID) or the first CLI argument.

set -euo pipefail

CLIENT_ID="${1:-${VITE_GOOGLE_CLIENT_ID:-}}"
if [[ -z "$CLIENT_ID" ]]; then
  echo "error: pass the Google client ID as \$1 or set VITE_GOOGLE_CLIENT_ID" >&2
  exit 1
fi

for cmd in curl jq openssl; do
  if ! command -v "$cmd" >/dev/null; then
    echo "error: $cmd is required" >&2
    exit 1
  fi
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/couchdb/jwt-keys.ini"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "; Generated by scripts/refresh-jwt-keys.sh on $(date -u +%FT%TZ)" > "$TMP"
echo "; Google ID tokens are signed with one of these RSA keys; CouchDB" >> "$TMP"
echo "; selects the right one via the JWT's \`kid\` header." >> "$TMP"
echo >> "$TMP"
echo "[jwt_keys]" >> "$TMP"

JWKS="$(curl -fsSL https://www.googleapis.com/oauth2/v3/certs)"
NUM_KEYS=$(printf '%s' "$JWKS" | jq '.keys | length')
if [[ "$NUM_KEYS" -lt 1 ]]; then
  echo "error: no keys returned from Google JWKS endpoint" >&2
  exit 1
fi

# Convert each JWK (RSA modulus n, exponent e) to a PEM SubjectPublicKeyInfo
# block. CouchDB expects the PEM content on a single line with literal \n
# between header/body lines.
for i in $(seq 0 $((NUM_KEYS - 1))); do
  KID=$(printf '%s' "$JWKS" | jq -r ".keys[$i].kid")
  N=$(printf '%s' "$JWKS"   | jq -r ".keys[$i].n")
  E=$(printf '%s' "$JWKS"   | jq -r ".keys[$i].e")

  # Pad base64url to a multiple of 4, swap url-safe alphabet, then decode to bytes.
  decode_b64url() {
    local s="$1"
    s="${s//-/+}"; s="${s//_//}"
    while [[ $(( ${#s} % 4 )) -ne 0 ]]; do s+='='; done
    printf '%s' "$s" | base64 -d
  }

  N_HEX=$(decode_b64url "$N" | xxd -p -c 99999)
  E_HEX=$(decode_b64url "$E" | xxd -p -c 99999)

  # Build an ASN.1 DER RSAPublicKey { modulus, publicExponent } and wrap it
  # in SubjectPublicKeyInfo. Using openssl asn1parse-driven generation:
  PEM=$(python3 - "$N_HEX" "$E_HEX" <<'PY'
import sys, base64

def i2osp(i):
    h = f"{i:x}"
    if len(h) % 2: h = "0" + h
    return bytes.fromhex(h)

def der_int(i):
    body = i2osp(i)
    if body[0] & 0x80:
        body = b"\x00" + body
    return b"\x02" + der_len(len(body)) + body

def der_len(n):
    if n < 128: return bytes([n])
    body = i2osp(n)
    return bytes([0x80 | len(body)]) + body

def der_seq(*parts):
    body = b"".join(parts)
    return b"\x30" + der_len(len(body)) + body

def der_bitstring(b):
    return b"\x03" + der_len(len(b) + 1) + b"\x00" + b

def der_null():
    return b"\x05\x00"

def der_oid_rsa():
    # 1.2.840.113549.1.1.1
    return bytes.fromhex("06092a864886f70d010101")

n = int(sys.argv[1], 16)
e = int(sys.argv[2], 16)
rsa_pub = der_seq(der_int(n), der_int(e))
spki = der_seq(der_seq(der_oid_rsa(), der_null()), der_bitstring(rsa_pub))
b64 = base64.b64encode(spki).decode()
lines = [b64[i:i+64] for i in range(0, len(b64), 64)]
pem = "-----BEGIN PUBLIC KEY-----\n" + "\n".join(lines) + "\n-----END PUBLIC KEY-----"
print(pem)
PY
)

  # CouchDB's INI parser wants the value on one line. Replace newlines with
  # the literal two-character sequence \n, which the JWT auth module decodes.
  PEM_INLINE="${PEM//$'\n'/\\n}"
  printf 'rsa:%s = %s\n' "$KID" "$PEM_INLINE" >> "$TMP"
done

cat >> "$TMP" <<EOF

[jwt_auth]
required_iss = https://accounts.google.com
required_aud = ${CLIENT_ID}
EOF

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote $OUT with $NUM_KEYS key(s)"
